name: Test changed packages
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '22' }

      - name: Find and test changed package roots
        shell: bash
        run: |
          set -euo pipefail

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE="${{ github.event.pull_request.base.sha }}"
          else
            BASE="${{ github.event.before }}"
            [ "$BASE" = "0000000000000000000000000000000000000000" ] && BASE="$(git rev-list --max-parents=0 HEAD)"
          fi

          # Collect nearest ancestor dirs that contain package.json
          changed_pkg_dirs=$(git diff --name-only -z "$BASE"...HEAD \
            | awk -v RS='\0' 'NF { print }' \
            | while IFS= read -r file; do
                dir=$(dirname "$file")
                while [ "$dir" != "." ] && [ "$dir" != "/" ]; do
                  if [ -f "$dir/package.json" ]; then
                    printf '%s\0' "$dir"
                    break
                  fi
                  dir=$(dirname "$dir")
                done
              done \
            | sort -zu \
            | tr '\0' '\n')

          if [ -z "$changed_pkg_dirs" ]; then
            echo "No changed package roots detected. Exiting."
            exit 0
          fi

          echo "Will test:"
          echo "$changed_pkg_dirs"

          # Run tests per unique package root
          while IFS= read -r d; do
            echo "::group::Testing $d"
            ( cd "$d" && (npm ci --prefer-offline --no-audit --fund=false || npm install) && npm test )
            echo "::endgroup::"
          done <<< "$changed_pkg_dirs"
